<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="0" failed="6" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Stop_11-29-2019 15-04-19.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Stop_11-29-2019 15-04-20full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Stop_11-29-2019 15-04-20.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Stop_11-29-2019 15-04-21full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_reStart_11-29-2019 15-04-26.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_reStart_11-29-2019 15-04-27full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_reStart_11-29-2019 15-04-27.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_reStart_11-29-2019 15-04-28full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_dump_Threads_11-29-2019 15-04-33.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_dump_Threads_11-29-2019 15-04-34full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_dump_Threads_11-29-2019 15-04-34.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_dump_Threads_11-29-2019 15-04-35full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_rolling_Restart_11-29-2019 15-04-40.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_rolling_Restart_11-29-2019 15-04-41full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_rolling_Restart_11-29-2019 15-04-41.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_rolling_Restart_11-29-2019 15-04-42full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_hard_Stop_11-29-2019 15-04-47.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_hard_Stop_11-29-2019 15-04-48full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_hard_Stop_11-29-2019 15-04-48.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_hard_Stop_11-29-2019 15-04-49full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Start_11-29-2019 15-04-55.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Start_11-29-2019 15-04-55full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Start_11-29-2019 15-04-56.jpg height='100' width='100'/>]]>
    </line>
    <line>
      <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Start_11-29-2019 15-04-57full_scren.jpg alt=yes height='100' width='100'/>]]>
    </line>
  </reporter-output>
  <suite started-at="2019-11-29T09:32:08Z" name="Suite" finished-at="2019-11-29T09:34:58Z" duration-ms="169228">
    <groups>
    </groups>
    <com.OCI.test.test started-at="2019-11-29T09:32:08Z" name="Regressionnew" finished-at="2019-11-29T09:34:58Z" duration-ms="169228">
      <class name="RCC.TestCases.TssApplication_Container_Operations">
        <com.OCI.test.test-method is-config="true" signature="openBrowser()[pri:0, instance:RCC.TestCases.TssApplication_Container_Operations@17f7cd29]" started-at="2019-11-29T09:32:03Z" name="openBrowser" finished-at="2019-11-29T09:32:08Z" duration-ms="5689" status="PASS">
          <reporter-output>
          </reporter-output>
        </com.OCI.test.test-method> <!-- openBrowser -->
        <com.OCI.test.test-method is-config="true" signature="tss_Login()[pri:0, instance:RCC.TestCases.TssApplication_Container_Operations@17f7cd29]" started-at="2019-11-29T09:32:08Z" name="tss_Login" finished-at="2019-11-29T09:32:24Z" duration-ms="15101" status="PASS">
          <reporter-output>
          </reporter-output>
        </com.OCI.test.test-method> <!-- tss_Login -->
        <com.OCI.test.test-method signature="Stop()[pri:1, instance:RCC.TestCases.TssApplication_Container_Operations@17f7cd29]" started-at="2019-11-29T09:32:24Z" name="Stop" finished-at="2019-11-29T09:34:19Z" duration-ms="115300" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at RCC.TestCases.TssApplication_Container_Operations.Stop(TssApplication_Container_Operations.java:103)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Stop_11-29-2019 15-04-19.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Stop_11-29-2019 15-04-20full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Stop_11-29-2019 15-04-20.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Stop_11-29-2019 15-04-21full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
          </reporter-output>
        </com.OCI.test.test-method> <!-- Stop -->
        <com.OCI.test.test-method signature="reStart()[pri:2, instance:RCC.TestCases.TssApplication_Container_Operations@17f7cd29]" started-at="2019-11-29T09:34:21Z" name="reStart" finished-at="2019-11-29T09:34:26Z" duration-ms="5164" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at RCC.TestCases.TssApplication_Container_Operations.reStart(TssApplication_Container_Operations.java:227)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_reStart_11-29-2019 15-04-26.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_reStart_11-29-2019 15-04-27full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_reStart_11-29-2019 15-04-27.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_reStart_11-29-2019 15-04-28full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
          </reporter-output>
        </com.OCI.test.test-method> <!-- reStart -->
        <com.OCI.test.test-method signature="dump_Threads()[pri:3, instance:RCC.TestCases.TssApplication_Container_Operations@17f7cd29]" started-at="2019-11-29T09:34:28Z" name="dump_Threads" finished-at="2019-11-29T09:34:33Z" duration-ms="5115" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at RCC.TestCases.TssApplication_Container_Operations.dump_Threads(TssApplication_Container_Operations.java:284)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_dump_Threads_11-29-2019 15-04-33.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_dump_Threads_11-29-2019 15-04-34full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_dump_Threads_11-29-2019 15-04-34.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_dump_Threads_11-29-2019 15-04-35full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
          </reporter-output>
        </com.OCI.test.test-method> <!-- dump_Threads -->
        <com.OCI.test.test-method signature="rolling_Restart()[pri:4, instance:RCC.TestCases.TssApplication_Container_Operations@17f7cd29]" started-at="2019-11-29T09:34:35Z" name="rolling_Restart" finished-at="2019-11-29T09:34:40Z" duration-ms="5086" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at RCC.TestCases.TssApplication_Container_Operations.rolling_Restart(TssApplication_Container_Operations.java:341)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_rolling_Restart_11-29-2019 15-04-40.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_rolling_Restart_11-29-2019 15-04-41full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_rolling_Restart_11-29-2019 15-04-41.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_rolling_Restart_11-29-2019 15-04-42full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
          </reporter-output>
        </com.OCI.test.test-method> <!-- rolling_Restart -->
        <com.OCI.test.test-method signature="hard_Stop()[pri:5, instance:RCC.TestCases.TssApplication_Container_Operations@17f7cd29]" started-at="2019-11-29T09:34:42Z" name="hard_Stop" finished-at="2019-11-29T09:34:47Z" duration-ms="5169" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at RCC.TestCases.TssApplication_Container_Operations.hard_Stop(TssApplication_Container_Operations.java:399)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_hard_Stop_11-29-2019 15-04-47.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_hard_Stop_11-29-2019 15-04-48full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_hard_Stop_11-29-2019 15-04-48.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_hard_Stop_11-29-2019 15-04-49full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
          </reporter-output>
        </com.OCI.test.test-method> <!-- hard_Stop -->
        <com.OCI.test.test-method signature="Start()[pri:6, instance:RCC.TestCases.TssApplication_Container_Operations@17f7cd29]" started-at="2019-11-29T09:34:49Z" name="Start" finished-at="2019-11-29T09:34:54Z" duration-ms="5101" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at RCC.TestCases.TssApplication_Container_Operations.Start(TssApplication_Container_Operations.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Start_11-29-2019 15-04-55.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Start_11-29-2019 15-04-55full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Start_11-29-2019 15-04-56.jpg height='100' width='100'/>]]>
            </line>
            <line>
              <![CDATA[<img src=D:\OCIAutomation\src\Screenshots\Failure_Start_11-29-2019 15-04-57full_scren.jpg alt=yes height='100' width='100'/>]]>
            </line>
          </reporter-output>
        </com.OCI.test.test-method> <!-- Start -->
        <com.OCI.test.test-method is-config="true" signature="tss_Logout()[pri:0, instance:RCC.TestCases.TssApplication_Container_Operations@17f7cd29]" started-at="2019-11-29T09:34:57Z" name="tss_Logout" finished-at="2019-11-29T09:34:58Z" duration-ms="1162" status="PASS">
          <reporter-output>
          </reporter-output>
        </com.OCI.test.test-method> <!-- tss_Logout -->
        <com.OCI.test.test-method is-config="true" signature="closeBrowser()[pri:0, instance:RCC.TestCases.TssApplication_Container_Operations@17f7cd29]" started-at="2019-11-29T09:34:58Z" name="closeBrowser" finished-at="2019-11-29T09:35:00Z" duration-ms="2096" status="PASS">
          <reporter-output>
          </reporter-output>
        </com.OCI.test.test-method> <!-- closeBrowser -->
      </class> <!-- RCC.TestCases.TssApplication_Container_Operations -->
    </com.OCI.test.test> <!-- Regressionnew -->
  </suite> <!-- Suite -->
</testng-results>
